on: 
  workflow_dispatch:

jobs:

  secrets_to_env_vars:
    runs-on: ubuntu-latest

    environment: dev

    name: Secrets to env vars test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: All secrets to environment variables
        uses: ./ # Uses an action in the root directory
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Show secret env var
        run: echo "TEST_REPOSITORY_SECRET = $TEST_REPOSITORY_SECRET"

      - name: Filtered secrets to environment variables
        uses: ./ # Uses an action in the root directory
        with:
          secrets: ${{ toJSON(secrets) }}
          secret_filter_regex: TEST_*

      - name: Show secret env var
        run: echo "TEST_REPOSITORY_SECRET = $TEST_REPOSITORY_SECRET"
      
      - name: Filtered secrets to with lower case transformation
        uses: ./ # Uses an action in the root directory
        with:
          secrets: ${{ toJSON(secrets) }}
          secret_filter_regex: TEST_*
          env_var_name_lower_case_regex: (?<=TEST_).*

      - name: Show secret env var
        run: echo "TEST_repository_secret= $TEST_repository_secret"
      - name: Get secret from store
        run: |
          echo "${{ secrets.TEST_VAR_2 }}"
          echo "${{ secrets.TEST_VAR_2 }}" > ./tempy
          cat tempy
          
